version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: social-auth-app:latest
    container_name: social-auth-app
    pull_policy: never
    env_file:
      - .env
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/social-auth
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: